import type { Metadata, Viewport } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import LoginToast from "@/components/ui/LoginToast";
import DialogProvider from "@/components/ui/DialogProvider";

const SITE_URL = "https://www.radiologist.lk";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Sri Lanka College of Radiologists",
  description:
    "Aligned with the Postgraduate Institute of Medicine, University of Colombo, the college is committed to training competent Radiologists and Radiotherapists. To Enlighten & Relieve.",
  applicationName: "Sri Lanka College of Radiologists",
  keywords: [
    "Sri Lanka College of Radiologists",
    "SLCR",
    "radiology Sri Lanka",
    "radiologist",
    "PGIM",
    "medical imaging",
    "academic sessions",
  ],
  authors: [{ name: "Sri Lanka College of Radiologists" }],
  creator: "Sri Lanka College of Radiologists",
  publisher: "Sri Lanka College of Radiologists",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_LK",
    url: SITE_URL,
    siteName: "Sri Lanka College of Radiologists",
    title: "Sri Lanka College of Radiologists",
    description:
      "Aligned with the Postgraduate Institute of Medicine, University of Colombo, the college is committed to training competent Radiologists and Radiotherapists.",
    images: [
      {
        url: "/images/og-default.png",
        width: 1200,
        height: 630,
        alt: "Sri Lanka College of Radiologists",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Sri Lanka College of Radiologists",
    description:
      "Aligned with the Postgraduate Institute of Medicine, University of Colombo, the college is committed to training competent Radiologists and Radiotherapists.",
    images: ["/images/og-default.png"],
  },
  icons: {
    // Stable public URLs (Google prefers these). File-based app/favicon.ico +
    // app/icon.png + app/apple-icon.png are also generated by Next.js.
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/images/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/images/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/images/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/images/icon-192.png", sizes: "192x192", type: "image/png" }],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0D1442",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable} ${montserrat.variable}`}>
      <body className="min-h-dvh font-sans antialiased">
        <DialogProvider>{children}</DialogProvider>
        <LoginToast />
        <Analytics />
      </body>
    </html>
  );
}
